name: 'Fluidity Docker Action'
description: 'Builds a docker container using github'
author: 'its'
branding:
  icon: 'package'
  color: 'purple'
inputs:
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password'
    required: true
  repository:
    description: 'Repository on registry'
    required: true
  pat:
    description: 'Personal Access Token'
    required: true
  pat_string:
    description: 'Personal Access string for .git-configuration'
    required: true
  registry:
    description: 'Registry hostname'
    required: false
  tag:
    description: 'Image tag'
    required: false

outputs:
  image:
    description: 'Tagged docker image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.repository }}
    - ${{ inputs.pat }}
    - ${{ inputs.pat_string }}
    - ${{ inputs.registry }}
    - ${{ inputs.tag }}
