name: 'Fluidity Docker Action'
description: 'Builds a docker container using github'
author: 'its'
branding:
  icon: 'package'
  color: 'purple'
inputs:
  username:
    description: 'Dockerhub Registry username'
    required: true
  password:
    description: 'Dockerhub Registry password'
    required: true
  repository:
    description: 'Github Repository name'
    required: true
  docker_repository:
    description: 'Docker repository name to push to'
    required: true
  registry:
    description: 'Docker Registry hostname'
    required: true
  pat_string:
    description: 'Personal Access string for .git-configuration to allow private repos to be  cloned'
    required: true
  tag:
    description: 'Docker Image tag name'
    required: false

outputs:
  image:
    description: 'Tagged docker image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.repository }}
    - ${{ inputs.docker_repository }}
    - ${{ inputs.registry }}
    - ${{ inputs.pat_string }}
    - ${{ inputs.tag }}